# This is a basic workflow to help you get started with Actions

name: PMD Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  pmd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI 
        run: |
                mkdir -p ~/cli/sf
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz | tar xJ -C ~/cli/sf --strip-components 1
                export PATH=~/cli/sf/bin:$PATH
                echo "$PATH" >> $GITHUB_PATH
                echo "path is : ${PATH}"
                echo "github path is : ${GITHUB_PATH}"
                sf --version
                

      - name:  Run PMD Scanner
        run: |
           #sf scanner run --target force-app --outfile --help
           sf scanner run --target force-app --outfile results.html,results.csv

      - name: Upload PMD Scanner reports
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: ./results.html
        
