# This is a basic workflow to help you get started with Actions

name: PMD Scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  pmd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI 
        run: |
                mkdir -p ~/cli/sf
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz | tar xJ -C ~/cli/sf --strip-components 1
                export PATH=~/cli/sf/bin:$PATH
                echo "$PATH" >> $GITHUB_PATH
                echo "path is : ${PATH}"
                echo "github path is : ${GITHUB_PATH}"
                sf --version
                sf plugins install @salesforce/sfdx-scanner.
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name:  Setup PMD Scanner
        run: |
           sf plugins install @salesforce/sfdx-scanner.
           sf scanner run
        
